# Generated by Django 4.2.2 on 2023-06-09 07:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(help_text='Загрузите вашу фотографию', upload_to='media/', verbose_name='Аватар'),
        ),
    ]
