# Generated by Django 4.2.2 on 2023-06-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_laptitude_user_longitude'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('laptitude__gte', -90.0), ('laptitude__lte', 90.0)), name='laptitude_between_minus90_90'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), name='longitude_between_minus180_180'),
        ),
    ]
