# Generated by Django 4.2.2 on 2023-06-11 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_laptitude_between_minus90_90_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='laptitude_between_minus90_90',
        ),
        migrations.RemoveField(
            model_name='user',
            name='laptitude',
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=54.9827385, help_text='Укажите широту вашего местоположения', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=82.8977945, help_text='Укажите долготу вашего местоположения', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), name='laptitude_between_minus90_90'),
        ),
    ]
